### PR TITLE
docker-entrypoint.sh: use exec

### LINKED ISSUE #24: Use exec in entrypoint to propagate signals to node
When you just call "node" in the shell script, that is used as entrypoint, it spawns a child process of "node". The problem with that is, that shell does not propagate the signals it receives from Docker to the children. Therefore the `SIGTERM` is not sent to node to terminate gracefully, only the `SIGKILL` is cutting of the process 10 seconds later.

(see https://www.ctl.io/developers/blog/post/gracefully-stopping-docker-containers/ for detailed explanation).

It would be recommended to use `exec lounge` in the last line, so basically lounge is running as `PID 1` inside the container, and a stopping the container would not look like this strace:

```
[pid 16173] open("/home/lounge/data/users", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 40
[pid 16173] fcntl(40, F_SETFD, FD_CLOEXEC) = 0
[pid 16173] getdents64(40, /* 4 entries */, 2048) = 112
[pid 16173] getdents64(40, /* 0 entries */, 2048) = 0
[pid 16173] close(40)                   = 0
[pid 16173] epoll_wait(5,  <unfinished ...>
[pid 16189] +++ killed by SIGKILL +++
[pid 16191] +++ killed by SIGKILL +++
[pid 16190] +++ killed by SIGKILL +++
[pid 16188] +++ killed by SIGKILL +++
[pid 16180] +++ killed by SIGKILL +++
[pid 16179] +++ killed by SIGKILL +++
[pid 16178] +++ killed by SIGKILL +++
[pid 16177] +++ killed by SIGKILL +++
[pid 16176] +++ killed by SIGKILL +++
+++ killed by SIGKILL +++

```

### PR DESCRIPTION
**Pull request by williamboman**
Fixes #24.

@matya Thoughts?

### CODE REVIEW

**Comment by matya** [comment]
Sorry for the delay. I'd rather suggest just prepending `exec` to the invocation, all other shell-magic is not necessary, as there are no other procedures after the server thread exits, so exec'ing would make it more bullet-proof.

**Comment by williamboman** [comment]
Ah, gotcha. I'm not very familiar with `exec`. Cool stuff

**Comment by matya** [comment]
Exec does not fork a process (as a child of the current one), but "replaces" it self with the target binary, which is basically inheriting the context of the original one. More info available via google (like https://en.wikipedia.org/wiki/Exec_(system_call))

**Comment by williamboman** [comment]
@matya With `exec` the container still exits as `137`. The node process does not seem to receive the `SIGTERM`?

**Pull request merged**
