### PR TITLE
Add Dockerfile for Alpine Linux that runs Node 6

### PR DESCRIPTION
**Pull request by daGrevis**
More info about the image can be found on [my repo](https://github.com/daGrevis/docker-thelounge).

Some notes:

* It's based on Alpine Linux (image size is 186 MB instead of 679 MB),
* It runs Node 6 instead Node 4,
* It builds from Git revision every time.

Impaloo from #thelounge suggested me to create a pull request.

### CODE REVIEW

**Comment by daGrevis** [comment]
Related to #4.

**Comment by daGrevis** [comment]
As suggested by xPaw, building master is not something we want. I added a build option for Git revision.

Here's how one could build Git tag `v2.0.0-pre.1`:

```sh
docker build --build-arg GIT_REV=v2.0.0-pre.1 -t mylounge .
```

**Comment by astorije** [comment]
Do we want to add some doc on this repo or https://github.com/thelounge/thelounge.github.io/blob/master/_docs/deployment/docker.md for this as well?

**Comment by daGrevis** [comment]
> The images in this repo targets (npm) releases of The Lounge, so the entire process of installing git to checking out a specific git ref is not very desired (imo).

But it's a feature! 🐛 

> Simply RUN npm install -g thelounge@${LOUNGE_VERSION} should do it.

This won't work on Git revisions.

There was this moment a few weeks ago when I wanted to update Lounge, but the latest version was slightly broken (session problem iirc). Master branch was fixed already so I thought I will just use that. Unfortunately you can't install `master` using current image. So I made one that's more flexible. As a side-effect, I switched to Alpine Linux and Node 6.

> This image would also need to be compatible with the main Dockerfile in terms of file paths (/home/lounge/data) and environment variables (LOUNGE_VERSION, LOUNGE_HOME).

My goal wasn't drop-in replacement for official image so I just assumed that defaults are fine. Directory will be mapped to something sensible when specifying mount-points anyway.

> Do we want to add some doc on this repo

Some docs probably should need to be extracted from [my repo](https://github.com/daGrevis/docker-thelounge).

I see this as an alternative way for installing Lounge, useful for when you know what you want.

**Comment by williamboman** [comment]
Replaced by #21.

**Pull request closed without merging**
